### ISSUE TITLE
Docker image is too large

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-de-amor#280]
According to @rennerocha and @paulochf our Docker image is too large. What can be done to get us in a better scenario?

I appreciate @Irio's effort in [this discussion](ttps://github.com/datasciencebr/serenata-de-amor/pull/270): organizing our repositories in submodules allowing us to orchestrate various containers in a seamless way.

If we have a neat Docker environment as such we could have our images on Docker Hub, what would decrease download size considerably – I guess.

Surely we can generate images on Docker Hub from now, but documenting ever-changing, non-mature images might create a version/documentation overhead. That's why I like the idea of orchestrating tihs flow.

Any other ideas that would made our images smaller?

**Comment by cauebs** [comment]
Perhaps the changes proposed by https://github.com/datasciencebr/rosie/pull/41 are now more relevant?

**Comment by viniciusartur** [comment]
I like the idea of changes that cause the smallest impact possible. So what changes with minimum impact could we do to reach this goal of having smaller Docker images?
Basic refactoring like:
- RUN command: only one per Dockerfile if possible
- COPY command: only one copying a compressed file, then on RUN we extract and copy to the right paths
The question is: if I would do this refactoring how smaller would be the Docker image? Would I have real benefits? 
It's important to see the big picture: If I would do this refactoring in all the Docker images of the Project how much I would gain?
The less I change, the less risks I take with bugs or incidents.

**Comment by caduvieira** [comment]
Our base image is 2 GB large. https://microbadger.com/images/jupyter/datascience-notebook

We only add 10% of it's size (2.2GB) https://microbadger.com/images/datasciencebr/serenata-de-amor

Do we need all that conda's libs to work? We could refactor our Dockerfile but the gain would be marginal at best if we don't  change the base image or create the environment ourselves.

**Comment by cuducos** [comment]
> Our base image is 2 GB large. https://microbadger.com/images/jupyter/datascience-notebook
> We only add 10% of it's size (2.2GB) https://microbadger.com/images/datasciencebr/serenata-de-amor

This is very important! Thanks for these stats ; )

>  all that conda's libs to work

Do you mean the ones in the `conda_requirements.txt` or the ones installed by default in Anaconda?

**Comment by ocefpaf** [comment]
Apologies if this is non-pertinent to the topic, but I've been following this repo and I have my two cents to give on this issue:

- the `datascience-notebook` image seems like an overkill to start here I would use the `minimal-notebook`, `base-notebook`, or even a [bare bones miniconda image](https://hub.docker.com/r/continuumio/miniconda) and install Jupyter there using the `conda_requirements.txt` (it would also be nice to rename it to `environment.yml` and list the channels used, env name, etc... More metadata for reproducibility in a single file);
- avoid images with the Anaconda distribution and always prefer `miniconda` instead to prevent "bloating" with unused software.

**Comment by alexsandro-xpt** [comment]
I have the same problem with it in my Python's project.

**Comment by caduvieira** [comment]
> Do you mean the ones in the conda_requirements.txt or the ones installed by default in Anaconda?

I mean https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile#L39
and 
https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile#L20

that are added by the base image.

And to be clear the 2GB are the download size. Once you unzip it's about 5.5GB

**Comment by cuducos** [comment]
Ok, good to know Miniconda is available in a Python 3 edition, yay ; )

Regrading the [R packages including IRKernel](https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile#L39) there was a PR using R and we might want to bring it onboard one of these days. However the PR is idle for months and IMHO we shouldn't push us to do that in this issue — this should be done when bringing the R notebook to `master`.

Regarding the list of [Conda dependencies](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile#L20) by heart I can say we use some of them (`scikit-learn`, `pandas`, `matplotlib`, `seaborn`, `bokeh`, `beautifulsoup4`) bur surely this doesn't mean we use _all of them_. I bet this repo doesn't depend on `sqlalchemy` for example… I think we could take the risk of cut some of them off, using a global search into the project source code to check if they're not imported anywhere…

And, again, I would consider that rosk together with @viniciusartur's question:

> The question is: if I would do this refactoring how smaller would be the Docker image? Would I have real benefits?

Or, as @caduvieira said: how far can we get considering the 2Gb we have today?

**Comment by ocefpaf** [comment]
> Regrading the R packages including IRKernel there was a PR using R and we might want to bring it onboard one of these days.

You don't need to rely on that Docker image to get the R packages. They can be listed in the `environment.yml` [like this](https://github.com/ioos/notebooks_demos/blob/master/environment.yml#L77-L94). Note that the "state" of the docker image bloats a little bit for each `RUN` call, so it is best to install everything in a single call.

**Comment by caduvieira** [comment]
We could use multiple runs to prevent an invalidation of a docker cache that we didn't need like this https://stackoverflow.com/questions/34398632/docker-how-to-run-pip-requirements-txt-only-if-there-was-a-change

**Comment by paulochf** [comment]
Thanks for bringing me here!

Actually, I don't know Docker really well. What I learned about it was during Serenata's SP Sprint haha.

What I do know is that we have an ML project at work that we are using a Docker base image based (strange phrasing, but I'll get it) on alpine which has Python 3.6 and Scikit+Pandas+Numpy+Scipy, and then our project uses it.

I'll talk to some people there and see what I can do for you, at least get the code for you to use as a reference.

**Comment by caduvieira** [comment]
> What I do know is that we have an ML project at work that my colleague @icaroseara crafted a Docker base image based (strange phrasing, but I'll get it) on alpine, which has Python 3.6 and Scikit+Pandas+Numpy+Scipy, and then our project uses it. Something like @cauebs pointed out.

Where are this image?

**Comment by icaroseara** [comment]
Hey @caduvieira, We do use the follow image at work to decrease the size of our ML projects.

https://hub.docker.com/r/empregoligado/alpine-python-ml/

**Comment by cuducos** [comment]
Agreed ; )
