### ISSUE TITLE
Question about installing environment with docker

### ISSUE THREAD

**Issue by netoferraz** [okfn-brasil/serenata-de-amor#296]
Hello guys! I'm following the project for a while, but only nowadays I'll try to help with something. My first try to set up the environment I'm encountering some troubles with recompile python to make things works properly,  as I don't know how to do that I decided to try with docker approach.  After some back and forth I got it. When I open the jupyter on my browser the folders structure has some differences with the repository. A new folder called work appears and looks to be a kind of copy of the research folder of the repository. I just wanna know if that's ok with my environment to work properly.

![folder structure](https://image.ibb.co/c0rAnm/main_folders.jpg)

![folder structure](https://image.ibb.co/cnVxYR/work.jpg)

**Comment by willianpaixao** [comment]
@cuducos the notebooks are no longer part of this repo. This issue should be closed.
