### ISSUE TITLE
Website Link in Readme is Incorrect

### ISSUE THREAD

**Issue by markwyner** [okfn-brasil/serenata-de-amor#330]
In the readme file you point to your official website, but the link is incorrect. I know that's not a part of the project itself, but for obvious reasons it’s still important.

You link to:
https://serenatadeamor.org/en

It redirects to:
https://serenata.aien/

It should redirect to:
https://serenata.ai/en/

I hope this helps.

**Comment by cuducos** [comment]
@Irio – assigned that to you as you're the DNS guy, ok?

**Comment by Irio** [comment]
Solved. Thanks @markwyner ;)

**Comment by markwyner** [comment]
It's my pleasure, friend.
