### ISSUE TITLE
Three undefined names

### ISSUE THREAD

**Issue by cclauss** [okfn-brasil/serenata-de-amor#338]
Flake8 testing of https://github.com/okfn-brasil/serenata-de-amor on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./research/src/fetch_inbox.py:21:18: F821 undefined name 'config'
EMAIL_PASSWORD = config('INBOX_PASSWORD')
                 ^
./research/src/fetch_sex_places.py:94:43: F821 undefined name 'config'
        self.url = GooglePlacesURL(key or config('GOOGLE_API_KEY'))
                                          ^
./research/src/fetch_sex_places.py:253:57: F821 undefined name 'url'
            logging.info('Timeout raised for {}'.format(url))
                                                        ^
3     F821 undefined name 'config'
```

**Comment by cuducos** [comment]
Hi @cclauss,

If you follow [the instructions](https://github.com/okfn-brasil/serenata-de-amor#settings) this errors go away. In other words, copy `contrib/.env.sample` as `.env`, and configure it properly before running the project ; )

Feel free to re-open the issue if you spot further problems, ok?
