### ISSUE TITLE
Remove (deleted) Dockerfile-nginx from Docker Cloud CI

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-de-amor#373]
The Ci is failing for `master`, one of the reasons is that it tries to build `Dockerfile-nginx` container – but this file was deleted, right? Here is [an example](https://cloud.docker.com/swarm/serenata/repository/docker/serenata/nginx/builds/e9a34800-834a-4dd6-92fe-e6d8ac89dd6e).

I couldn't find the proper settings in Docker Cloud, can you give me hand, @Irio?

**Comment by Irio** [comment]
Removed from Docker Cloud. ;)
