### ISSUE TITLE
How to install the example project

### ISSUE THREAD

**Issue by fabregasf** [okfn-brasil/serenata-de-amor#380]
I've cloned the project with git, and now I need to see in practice on the browser. But, how I do this? I run npm install and anything happens when I get: myserver/serenata-de-amor . 
![serenata](https://user-images.githubusercontent.com/10199180/39944124-b43f7f58-553b-11e8-98f2-599be7cbecdf.png)

**Comment by cuducos** [comment]
Hi @fabregasf, nice to see newcomers here : )

By any chance, were you able to find and test the instructions in our `CONTRIBUTING.md`? There's a link to it in the `README.md` that shows up in the home page for this project here at GitHub.

It seams likewhat you need ; )

Let me know how far you get, ok?

**Comment by cuducos** [comment]
Hi @fabregasf, nice to see newcomers here : )

By any chance, were you able to find and test the instructions in our `CONTRIBUTING.md`? There's a link to it in the `README.md` that shows up in the home page for this project here at GitHub.

It seams likewhat you need ; )

Let me know how far you get, ok?

**Comment by willianpaixao** [comment]
@cuducos the whole structure of the project changed since this ticket was opened. Should it be closed?

**Comment by cuducos** [comment]
True story
