### ISSUE TITLE
Problem with docker-compose up

### ISSUE THREAD

**Issue by r41278856** [okfn-brasil/serenata-de-amor#398]
**What is the problem?**
 I am trying to run rosie and generate the database suspicions. I am following this guide https://github.com/okfn-brasil/serenata-de-amor/blob/master/CONTRIBUTING.md. I am working in windows 10. Everything works until I run this command docker-compose up
Then I get this error
Building research
Step 1/11 : FROM conda/miniconda3
 ---> 7bd5d4e6b751
Step 2/11 : USER root
 ---> Using cache
 ---> b8f9486517d7
Step 3/11 : ARG AMAZON_BUCKET=serenata-de-amor-data
 ---> Using cache
 ---> 2c6dd284726e
Step 4/11 : ARG AMAZON_ENDPOINT=https://nyc3.digitaloceanspaces.com
 ---> Using cache
 ---> ed55f3100c81
Step 5/11 : ARG AMAZON_REGION=nyc3
 ---> Using cache
 ---> 37a21a74826a
Step 6/11 : RUN apt-get update     && apt-get install -y --no-install-recommends         unzip         libxml2-dev         libxslt-dev     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d74117b34185
Step 7/11 : WORKDIR /mnt/code
 ---> Using cache
 ---> 952ed0467153
Step 8/11 : COPY ./requirements.txt ./requirements.txt
 ---> Using cache
 ---> f6cb6adcd85e
Step 9/11 : COPY ./setup ./setup
 ---> Using cache
 ---> bb76b3c4a436
Step 10/11 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> d59460642708
Step 11/11 : RUN ./setup
 ---> Running in 3173993eb134
/usr/bin/env: 'python3\r': No such file or directory
ERROR: Service 'research' failed to build: The command '/bin/sh -c ./setup' returned a non-zero code: 127

@cuducos suggested me to replace python3 by python in the first line of this file and test if it works https://github.com/okfn-brasil/serenata-de-amor/blob/master/research/setup

But it doesn't work.
I get the same error with a small change
Step 11/11 : RUN ./setup
 ---> Running in 87c4e020af64
/usr/bin/env: 'python\r': No such file or directory
ERROR: Service 'research' failed to build: The command '/bin/sh -c ./setup' returned a non-zero code: 127

**How can this be addressed?**
@cuducos suggested that Continuum might have updated their Docker image

**Who could help with this issue?**
@cuducos

**Comment by cuducos** [comment]
Ok, my first guess was wrong: the latest image is 1 year old.

I guess it's a Windows issue related to the end of line (`\n\r` vs. `\n`). When `setup.py` is copied from Windows (host) to Linux (container) it goes with Windows line endings and crashes: note the `\r` in the error message `/usr/bin/env: 'python\r': No such file or directory`…

Can anyone with Windows (and maybe some Docker experience) test it to (in)validate this hypothesis?

Something @r41278856 can do: can you check there's no change in your local branch? What output does `git status` give you? Can you clean changes with `git checkout <every file from the last output>`?

**Comment by r41278856** [comment]
Thanks for your reply Eduardo. I am using windows.

Git states does this
\serenata-de-amor>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

I clon the folder again, I get a slightly different output, but it couldn't complete the task 

C:\Users\user\Dropbox\mres_dissertation\data\serenata-de-amor>docker-compose up
Building research
Step 1/11 : FROM conda/miniconda3
 ---> 7bd5d4e6b751
Step 2/11 : USER root
 ---> Using cache
 ---> b8f9486517d7
Step 3/11 : ARG AMAZON_BUCKET=serenata-de-amor-data
 ---> Using cache
 ---> 2c6dd284726e
Step 4/11 : ARG AMAZON_ENDPOINT=https://nyc3.digitaloceanspaces.com
 ---> Using cache
 ---> ed55f3100c81
Step 5/11 : ARG AMAZON_REGION=nyc3
 ---> Using cache
 ---> 37a21a74826a
Step 6/11 : RUN apt-get update     && apt-get install -y --no-install-recommends         unzip         libxml2-dev         libxslt-dev     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d74117b34185
Step 7/11 : WORKDIR /mnt/code
 ---> Using cache
 ---> 952ed0467153
Step 8/11 : COPY ./requirements.txt ./requirements.txt
 ---> 6789c5634903
Step 9/11 : COPY ./setup ./setup
 ---> 12ac15376b25
Step 10/11 : RUN pip install -r requirements.txt
 ---> Running in c874ccecb221
Collecting aiofiles==0.3.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0b/39/bb20653b60bab6ba036f13f7eae91a232b63394d4a04ae08efd45f434222/aiofiles-0.3.2-py3-none-any.whl
Collecting aiohttp==3.3.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/54/f9/8b47199ceae89a867edc45c43dc908384fd2e1ac22406b60d101d988752b/aiohttp-3.3.2-cp36-cp36m-manylinux1_x86_64.whl (876kB)
Collecting beautifulsoup4==4.6.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
Collecting geopy==1.14.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/9b/1b/f63484e2c257a79f9fed6243f638d0fc50566428b87994dbf2cdf681a05e/geopy-1.14.0-py2.py3-none-any.whl (77kB)
Collecting grequests==0.3.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/25/9f/dff6f21676ca5d3e806e60cf0a49c52eb8f8c859310d28b1e740bc49b93e/grequests-0.3.0.tar.gz
Collecting humanize==0.5.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting numpy==1.14.5 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (12.2MB)
Collecting pandas==0.23.3 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/f4/cb/a801eaf624e36fffaa6cf1f4597a1e4b0742c200ed928e689c58fb3cb811/pandas-0.23.3-cp36-cp36m-manylinux1_x86_64.whl (8.9MB)
Collecting python-decouple==3.1 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/9b/99/ddfbb6362af4ee239a012716b1371aa6d316ff1b9db705bfb182fbc4780f/python-decouple-3.1.tar.gz
Collecting requests==2.19.1 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
Collecting serenata-toolbox (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/03/e4/b7c274205acf6ce787ea0a48aff342447f82720fb88f10b381c40855ee6a/serenata_toolbox-15.0.3-py3-none-any.whl
Collecting tqdm==4.23.4 (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/93/24/6ab1df969db228aed36a648a8959d1027099ce45fad67532b9673d533318/tqdm-4.23.4-py2.py3-none-any.whl (42kB)
Collecting yarl<2.0,>=1.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/61/67/df71b367680e06bb4127e3df6189826d4b9daebf83c3bd5b9341c99ef528/yarl-1.2.6-cp36-cp36m-manylinux1_x86_64.whl (253kB)
Collecting async-timeout<4.0,>=3.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/96/0f/e6357458c87fb4ed8f3df215773f3caad40968f10e05552cbd8bd28415e4/async_timeout-3.0.0-py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna-ssl>=1.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
Collecting attrs>=17.3.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp==3.3.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/cc/30/508a22a28dfb50cf9079cd9d0cf9b0d7dbae5afdf9823977351cbd548897/multidict-4.3.1-cp36-cp36m-manylinux1_x86_64.whl (476kB)
Collecting geographiclib<2,>=1.49 (from geopy==1.14.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/5b/ac/4f348828091490d77899bc74e92238e2b55c59392f21948f296e94e50e2b/geographiclib-1.49.tar.gz
Collecting gevent (from grequests==0.3.0->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ef/71/48aa308c1a92475e89afbd1a45d6978ac69b007169c761f048a5c9336f2d/gevent-1.3.4-cp36-cp36m-manylinux1_x86_64.whl (4.5MB)
Collecting python-dateutil>=2.5.0 (from pandas==0.23.3->-r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
Collecting pytz>=2011k (from pandas==0.23.3->-r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
Collecting certifi>=2017.4.17 (from requests==2.19.1->-r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests==2.19.1->-r requirements.txt (line 10))
Collecting urllib3<1.24,>=1.21.1 (from requests==2.19.1->-r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
Collecting lxml>=3.6 (from serenata-toolbox->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/d1/81/5a3e70c8adc20fb295a2f4c9fdf09af8295c7a00ccec6ee3d31084cbf272/lxml-4.2.3-cp36-cp36m-manylinux1_x86_64.whl (5.9MB)
Collecting greenlet>=0.4.13; platform_python_implementation == "CPython" (from gevent->grequests==0.3.0->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/dd/ce/7b3a19a3eb8c79e6237ba1fb7a8729b39034dd2de8753b8d27e5abc59fd5/greenlet-0.4.13-cp36-cp36m-manylinux1_x86_64.whl (43kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas==0.23.3->-r requirements.txt (line 8))
Building wheels for collected packages: grequests, humanize, python-decouple, idna-ssl, geographiclib
  Running setup.py bdist_wheel for grequests: started
  Running setup.py bdist_wheel for grequests: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/00/3d/90/eb93eb8a1a2fdc6ce52ab85949b867beaed1e255a38a532901
  Running setup.py bdist_wheel for humanize: started
  Running setup.py bdist_wheel for humanize: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44
  Running setup.py bdist_wheel for python-decouple: started
  Running setup.py bdist_wheel for python-decouple: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/0f/ee/80/75b684060dc6ecc5a28c07b75ef4063f378aff1a37556f342a
  Running setup.py bdist_wheel for idna-ssl: started
  Running setup.py bdist_wheel for idna-ssl: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d3/00/b3/32d613e19e08a739751dd6bf998cfed277728f8b2127ad4eb7
  Running setup.py bdist_wheel for geographiclib: started
  Running setup.py bdist_wheel for geographiclib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/99/45/d1/14954797e2a976083182c2e7da9b4e924509e59b6e5c661061
Successfully built grequests humanize python-decouple idna-ssl geographiclib
Installing collected packages: aiofiles, multidict, yarl, async-timeout, chardet, idna-ssl, attrs, aiohttp, beautifulsoup4, geographiclib, geopy, greenlet, gevent, certifi, urllib3, requests, grequests, humanize, numpy, python-dateutil, pytz, pandas, python-decouple, tqdm, lxml, serenata-toolbox
  Found existing installation: requests 2.14.2
    Uninstalling requests-2.14.2:
      Successfully uninstalled requests-2.14.2
Successfully installed aiofiles-0.3.2 aiohttp-3.3.2 async-timeout-3.0.0 attrs-18.1.0 beautifulsoup4-4.6.0 certifi-2018.4.16 chardet-3.0.4 geographiclib-1.49 geopy-1.14.0 gevent-1.3.4 greenlet-0.4.13 grequests-0.3.0 humanize-0.5.1 idna-ssl-1.1.0 lxml-4.2.3 multidict-4.3.1 numpy-1.14.5 pandas-0.23.3 python-dateutil-2.7.3 python-decouple-3.1 pytz-2018.5 requests-2.19.1 serenata-toolbox-15.0.3 tqdm-4.23.4 urllib3-1.23 yarl-1.2.6
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container c874ccecb221
 ---> ecd32fd30b0d
Step 11/11 : RUN ./setup
 ---> Running in b7ff84621b3b
/usr/bin/env: 'python3\r': No such file or directory
ERROR: Service 'research' failed to build: The command '/bin/sh -c ./setup' returned a non-zero code: 127

C:\Users\user\Dropbox\mres_dissertation\data\serenata-de-amor>pip install --upgrade pip
ERROR: To modify pip, please run the following command:
c:\users\user\anaconda3\python.exe -m pip install --upgrade pip

C:\Users\user\Dropbox\mres_dissertation\data\serenata-de-amor>c:\users\user\anaconda3\python.exe -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\users\user\anaconda3\lib\site-packages (10.0.1)

**Comment by derrix060** [comment]
return code `127` means that the command was not found. Try to execute locally `bin/sh -c ./setup` and see what's going on. Maybe you will have to change your PATH.

**Comment by cuducos** [comment]
Makes sense ; )
