### ISSUE TITLE
New pip deprecated pip.main(…) used in setup script

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-de-amor#400]
**What is the problem?**

As @r41278856 reported [elsewhere](https://github.com/okfn-brasil/serenata-toolbox/pull/114#issuecomment-405942583) `pip` version 10 deprecated `pip.main(…)` (available on `pip` version 9).

**How can this be addressed?**

Some ideas (not exclusive ideas by the way)

* Updating `setup` script using new version of `pip` if it has an equivalent options
* Updating `setup` script using shell script instead of Python
* Locking `pip` version on dependencies file

**Who could help with this issue?**

IMHO this sounds like a very good issue for beginners ; )

**Comment by cuducos** [comment]
Personally I would get rid of `setup` and just add the `pip install` stuff to the docs ; )

**Comment by R3DDY97** [comment]
hi would like to fix it

will use new version pip equivalent

**Comment by cuducos** [comment]
Sorry, @silasalvares , it was alreadu fixed by #401 but we forgot to close this issue ; )
