### ISSUE TITLE
Jarbas API doesn't filter by state parameter

### ISSUE THREAD

**Issue by dumabg** [okfn-brasil/serenata-de-amor#402]
Trying the Jarbas API, the state parameter seems do nothing:

https://jarbas.serenata.ai/api/chamber_of_deputies/reimbursement/?limit=7&state=DF

Return all, not filtered by state.

**Comment by dumabg** [comment]
On the documentation, https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/README.md, appears on Filtering section.

**Comment by cuducos** [comment]
No, it doesn’t. It might be confusing (and surely we can work on to clarify this in the docs), but the link you and I referred to says the content of the `state` field is indexed in the query generated by the `search` filter.

We try to communicate this by the indentation and the hierarchy of a nested unordered list. I’m sorry it didn’t work. Any ideas to better communicate it?

**Comment by dumabg** [comment]
What do you think something like?

search. The value is searched in these fields:

and add in the sample the parameter search with, for exemple, DF, explainig that filters by state DF.

**Comment by dumabg** [comment]
What about put another parameter, searchfield?

**Comment by cuducos** [comment]
As [I just mentioned](https://github.com/okfn-brasil/serenata-de-amor/issues/402#issuecomment-406354463) adding `state` to the filters is indeed a good idea 🤘

But I do not belive that searching by state using the `search` field is very useful. If I got you example, `?search=DF` is not actually filtering reimbursements from DF congresspeople… it is searching for the string `DF` in a series of fields (which happens to include
`state`).

**Comment by dumabg** [comment]
How Jarbas Dashboard filter by state? It uses another API?

**Comment by cuducos** [comment]
> What about put another parameter, searchfield?
 
I really don’t see how `searchfield` might be better than simply `search`. Can you expand on that?

Regarding the dashboard, it doesn’t use any external API, it’s just Django Admin.

**Comment by dumabg** [comment]
on searchfield could be specified the field used for search. For exemple, in this case, could be something like searchfield=state&search=DF

**Comment by cuducos** [comment]
Hum… basically this would not work: the `search` happens in a pre-createda search vector, so you cannot choose whic field to look up. And enabling search in any firld without it would compromise our Postgres performance. I think the beat direction for this issue is to include state as a filtering field.

**Comment by cuducos** [comment]
Closed by #418
