### ISSUE TITLE
[question] where can I find the models used?

### ISSUE THREAD

**Issue by gcmartinelli** [okfn-brasil/serenata-de-amor#403]
Scanning the code I only found the import of existing (trained) models. I would like to learn more about the model itself. Is it shared somewhere? Maybe I missed it in the code... Thanks!

**Comment by cuducos** [comment]
Maybe @jtemporal @anaschwendler or @Irio can better address this question, but long story short we don't use per-existing models in Rosie. If I'm not wrong it can help that she trains a model and save it for later, but it's generated on-the-fly.

**Comment by gcmartinelli** [comment]
I believe I found the classifier locations now (in `rosie/rosie/chamber_of_deputies/classifiers` and `rosie/rosie/federal_senate/classifiers`). I appreciate the quick response :+1:
