### ISSUE TITLE
Automate searchvector creation

### ISSUE THREAD

**Issue by giovanisleite** [okfn-brasil/serenata-de-amor#425]
**What is the problem?**
Today the [searchvector](https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/search/) creation is made manually with the command `python manage.py searchvector` ([code](https://github.com/okfn-brasil/serenata-de-amor/blob/be9c2cf0d2a01d8895980f4eb83b51830034a0ee/jarbas/chamber_of_deputies/management/commands/searchvector.py)) and it could be **automated**.
This command should run every **48h**, between **2 am** and **4 am**.

**How can this be addressed?**
- Use the `jarbas/celery.py` file
- Create a function that schedule the execution of the management command to be executed every 48h ([schedule function example](https://github.com/okfn-brasil/diario-oficial/blob/83a0df9dc5f7664a79b4d1faee73fc78c6a8689d/processing/tasks.py#L19) - This example schedules to every day, 13 hours, [celery documentation brings other forms of scheduling](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html) ).
- Create the function that executes the `python manage.py searchvector` command ([execute a command example](https://github.com/okfn-brasil/diario-oficial/blob/83a0df9dc5f7664a79b4d1faee73fc78c6a8689d/processing/tasks.py#L61)).

**Who could help with this issue?**
I can help on sundays =)

**Labels**
[enhancement]

This issue is a translation of `Melhorias no Jarbas/Automatizar atualizações/1`, page 4 of [this document](https://docs.google.com/document/d/1qjYHKr9FLAaDwI4VJeHbcWj4LKrAWBeHqrB6VqBLXi8/edit#heading=h.6nco566ujoz0).

**Comment by luciakasman** [comment]
Hello! I would like to work on this issue :)

**Comment by giovanisleite** [comment]
Hey, @luciakasman, @oleggator already did this specific task, but in #497 there is a discussion about adding more things to the celery schedule, you could do it if you want.

Thanks for the interest!
