### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by willianpaixao** [okfn-brasil/serenata-de-amor#427]
This repo has currently 37 branches, many of them created by the _pyup-bot_, having its respective issue closed, but the branch remained. Some user created branches also, having up to two years with no new commits or rebase, being most likely forgotten or abandoned.

Some effort in checking whether the branch should be just deleted or some contributor could be pinged for either finishing its issue or documenting for another one pick it up.

**Comment by willianpaixao** [comment]
@jtemporal

**Comment by cuducos** [comment]
Unfortunately it looks like @pyup-bot [is not prepared to delete branches from closed non-merged PRs](https://pyup.io/docs/bot/config/), thus a palliative thing to do would be to change the schedule to once a month in out `.pyup.yml`. This could be done in a PR.

In spite of that we could manually clean-up stale branches, or add a script to be run by maintainers that would automatically clean-up stale branches. Personally I think that manually doing that is safer : ) What do you think about it? What else we might be missing?

**Comment by jtemporal** [comment]
I already deleted the pyup stale branches that I found. Other than that I would 

> change the schedule to once a month in our `.pyup.yml`.

as you suggested @cuducos 

Other than that... there are a lot of branches of unfinished hypothesis study or things that we didn't want to be merged into master for any kind of reasons... @willianpaixao could you specify what other branches you think should be removed?

**Comment by willianpaixao** [comment]
@jtemporal there's no official procedure for that, but we need to chase the developers who push those branches and kindly ask the status of their contributions, what's left to implement and if they can either finish or write a small guide to someone else that can pick up the left work.

Some branches are so old that they might implement something that is no longer desired or even compatible with the current state of the project. In this case, just make a comment on the issue and remove the branch (which will automatically close the PR related).

Which leads me to kindly suggest that the project could/should have a workflow issue -> branch -> PR. Where you can trace every branch/merge to an issue that was previously discussed and approved. This way you improve traceability and avoid devs work on issues that are not desired and would later be denied to merge (which happened quite recent). This could be simply added to the CONTRIBUTING.md and reinforced in the issue and PR templates.

**Comment by cuducos** [comment]
We did a clean up. There are still some stale and not merged branches we would like to keep for documentation (stuff we might link in a talk or another, for example). So I'm closing this issue — thanks for the heads up, @willianpaixao ; )
