### ISSUE TITLE
Removing goss from dependencies

### ISSUE THREAD

**Issue by willianpaixao** [okfn-brasil/serenata-de-amor#429]
I was looking at this health check service used in the Jarbas Docker image, [goss](https://github.com/aelsabbahy/goss).

It's a small dependency (<10MB according to its author), but it can be replaced with a simple line in `jarbas/urls.py` that adds a route (for example `/healthcheck`) that simply returns 200. Additionally, it would use `curl` which is already in the base image to request the route and verify the status of the web service.

**Comment by cuducos** [comment]
Just out of curiosity: if the point is to have a view that simply returns 200, can we use a regular endpoint instead?

**Comment by willianpaixao** [comment]
Precisely my friend. And right now we're using a 10MB external app for that.

**Comment by willianpaixao** [comment]
It could also return a json with some simple stats of the django application (eg number of active connections, etc), and this could be used for monitoring.
