### ISSUE TITLE
Automate the update process

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-de-amor#447]
**What is the problem?**
Nowadays we need to _manually_ update our dataset because we do not have money to keep a DigitalOcean droplet with 16Gb of RAM running. But we have to automate that anyway. The manual process is done roughly like that:

1. Run Rosie locally
2. Upload the two generated CSV to the production server manually with `scp`
3. Copy the two CSV to the Docker container with `docker cp`
4. Delete the files from the production server
5. Run the command to update the reimbursements
6. Run the command to update the suspicions
7. Delete the files from the container

**How can this be addressed?**

We need to warp the steps above in a script that:

1. Creates a DigitalOcean droplet with the required RAM (16Gb), they have an API for that
2. Installs Git and Docker
3. Clone this repo
4. Runs Rosie to generate the CSV
5. Run Jarbas connecting to the production database
6. Run the two update commands (reimbursements and suspicions)
7. Delete the droplet

**Who could help with this issue?**
@jtemporal @Irio @giovanisleite @willianpaixao @cabral

**Comment by andrewsmedina** [comment]
I can help with this issue.
