### ISSUE TITLE
Telegram group invitation link is expired

### ISSUE THREAD

**Issue by pnandikur** [okfn-brasil/serenata-de-amor#463]
Even after trying multiple time to send invitation getting following error :
Method: messages.checkChatInvite
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}

tg://join?invite=AAAAAEItvJql8VPs7QE8Tg

**Comment by cuducos** [comment]
Thanks for reporting, @pnandikur.

I assume you're referring to the Telegram group invitation link, right? If so, can you confirm this link works? If so we can open a PR: https://t.me/joinchat/ACJyTEBDOqp6uZIAeUEOlw

**Comment by maurokenny** [comment]
This link worked for me

**Comment by sergiomario** [comment]
The link shared by Eduardo Cuducos is working correctly.

**Comment by iammultiman** [comment]
Ask the admin to check Removed Users under Permissions. If your username is there, it should be cleared since such users cannot join via an invite link. Or ask the admin to add your username to the Add Exception list under Permissions.

**Comment by sfksuperman** [comment]
For me it's not working. I freshly installed new rom and new app (7.6.0.1 17550). And invite links are saying it's expired (screenshot provided).
I tried the above link you shared in this chat and it's expired too.

**Comment by sokhraksa** [comment]
https://t.me/+7nI7f1pIYK9hZTNI

**Comment by sokhraksa** [comment]
https://t.me/+7nI7f1pIYK9hZTNI

**Comment by sokhraksa** [comment]
> Even after trying multiple time to send invitation getting following error : Method: messages.checkChatInvite Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
> 
> tg://join?invite=AAAAAEItvJql8VPs7QE8Tg

https://t.me/+7nI7f1pIYK9hZTNI
