### ISSUE TITLE
Jarbas has a permission problem to access google maps api

### ISSUE THREAD

**Issue by sergiomario** [okfn-brasil/serenata-de-amor#470]
**What is the problem?**
In the suspicious reimbursements screen, the Street View images are displaying the following message:
`“this page didn’t load google maps correctly”`
I've checked that the Google Maps API requests are returning status code 403.

**How can this be addressed?**
An alternative would be to check if the Maps API access key is expired.

**Comment by cuducos** [comment]
I think this is a duplicate #441 ; )

**Comment by sergiomario** [comment]
Sure. Issue closed.
