### ISSUE TITLE
Reimbursement details CNPJ and Fornecedor doesn't match

### ISSUE THREAD

**Issue by luizfzs** [okfn-brasil/serenata-de-amor#505]
**What is the problem?**
While checking some reimbursement requests, I noticed that on the [details page](https://jarbas.serenata.ai/dashboard/chamber_of_deputies/reimbursement/37968096/change/?_changelist_filters=p%3D1%26q%3DEDUARDO%2BBOLSONARO) the CNPJ matches with the receipt but the 'Fornecedor' doesn't. 

**How can this be addressed?**
There might be an issue on the code that handles the parsing of receipts

**Who could help with this issue?**
Someone that is involved with the parsing module, or some adventurous person willing to explore the code

**Labels**
[bug] [jarbas]

**Comment by cuducos** [comment]
Thanks for opening the issue, @luizfzs, but Serenata does not edit data and this error is not related to our stack. You can verify the system of the Chamber of Deputies holds (and publicize) that inconsistency: https://www.camara.leg.br/cota-parlamentar/documento?nuDeputadoId=2907&numMes=4&numAno=2019&despesa=14&cnpjFornecedor=31297457000133&idDocumento=4743

You can report the matter to them, though: https://camara.custhelp.com/app/utils/login_form/redirect/home

Feel free to share here their reply ; )

**Comment by luizfzs** [comment]
Thank you for pointing that out. I'll report it and get back when (and if) they reply.

**Comment by luizfzs** [comment]
So, here's the response:

> Recebemos sua mensagem na Ouvidoria Parlamentar e a encaminhamos à Coordenação de Gestão da Cota Parlamentar - COGEP, que retornou o seguinte:
>  
> "...Ao confrontar a solicitação de reembolso encaminhada pelo parlamentar com a nota fiscal, anexa, constatamos tratar-se, de fato, de um erro material no pedido de reembolso...
>   
> Assim, procedemos aos ajustes pertinentes no sistema Cotasnet, para registrar o correto nome da pessoa jurídica emissora do comprovante da despesa, retificando os dados publicados do Portal Transparência"
>  
> Em anexo resposta na íntegra.
>  
> Atenciosamente,
>  
> Assessoria da Ouvidoria Parlamentar
> Ouvidor-Geral Deputado Eduardo Barbosa

I can see now that the information is correct on their website. I just checked the info on Jarbas and the info is not in sync. You may need to update it.

**Comment by cuducos** [comment]
Great, many thanks, @luizfzs! I'm not sure when the data was updated in their services, but AFAIK [Jarbas is updated every week at Monday 1am](https://github.com/okfn-brasil/serenata-de-amor/blob/ce10d2b23e2ea375e1e51919e3dcf3ae7db3f861/contrib/crontab/crontab#L5)

I'm cc-ing @sergiomario because I think he's the one with access to the server to check that.

**Comment by sergiomario** [comment]
Hi @cuducos and @luizfzs :-)

I investigated the weekly crons and really noticed an error in the weekly update, which hadn't occurred in months.

That way, I opened issue #506 with the error that is occurring in the Rosie classifier.
