### ISSUE TITLE
It's not clear weather the politician was reimbursed or not

### ISSUE THREAD

**Issue by luizfzs** [okfn-brasil/serenata-de-amor#512]
**What is the problem?**
On Jarbas '[Reembolsos](https://jarbas.serenata.ai/dashboard/chamber_of_deputies/reimbursement/?) dashboard, it's not clear which reimbursement requests were actually reimbursed.
I'm assuming that every entry on Jarbas is a reimbursement request, not an actual reimbursement.

**How can this be addressed?**
A new column can be added to either the Dashboard and the reimbursement details.
I would suggest something like the 'Suspeito' column. The column name could be something like 'Houve reembolso'

**Who could help with this issue?**
Someone with some sort of knowledge of how the reimbursements work. Also, someone who wants to work with Django :)

**Labels**
[jarbas]  [enhancement]

**Comment by cuducos** [comment]
> I'm assuming that every entry on Jarbas is a reimbursement request, not an actual reimbursement.

I'm afraid this is not the case. The Chamber of Deputies _only_ release data about reimbursement (actually reimbursed), not about reimbursement claims.

**Comment by luizfzs** [comment]
I didn't know it that was the case as not. Since it is, this issue is invalid.
