### ISSUE TITLE
Design and development of the situation beem weapons and development of ship Eco sestoum fist and control over

### ISSUE THREAD

**Issue by 0regard** [okfn-brasil/serenata-de-amor#521]
This template is here to help you to write your issue ;)

**What is the problem?**
Try to give as many details about the bug/new feature/enhancement as possible,
but keep it friendly for new comers

**How can this be addressed?**
New comers might need help on how to approach or build a solution, maybe a
step-by-step on how to address the issue can help

**Who could help with this issue?**
We know sometimes a good session of pair programming can do wonders, maybe
indicate someone that can be reached to help out and discuss ideas. If you
don't know someone but is up for a pair programming session use this space to
tell us o/

**Labels**
Feel free to write up labels that you think might apply here. e.g.
[first-timers-only]  [bug]

**Comment by 0regard** [comment]
![15856725888761748128651971022345](https://user-images.githubusercontent.com/62855008/78051979-b3800e00-733b-11ea-8c35-dd4710c253d9.jpg)

**Comment by cuducos** [comment]
Reported as #spam.
