### ISSUE TITLE
Installation using requirements.txt without Anaconda fails

### ISSUE THREAD

**Issue by coelhudo** [okfn-brasil/serenata-de-amor#532]
**What is the problem?**

Just invoking `pip install -r requirements.txt` doesn't work in an environment without Anaconda.

For example, scikit-learn or pandas are not part of the dependencies listed.

Since not everyone uses Anaconda, offering another option could improve the project.

**How can this be addressed?**

An alternative file, that uses the requirements.txt file as dependency, could be provided.

[enhancement]  [documentation]

**Comment by abhinand5** [comment]
A pip version of the requirements file was added here #536

**Comment by cuducos** [comment]
In my opinion this is not an issue at all. The project was not design to work like that (with bare `pip`) for a reason: reduce first-time contributors barriers.

I also highlight what I commented in the related PR:

> This `pip` version suggested here would only work if the user already has a series of dependencies installed in their OS — this would make the system ready to compile under the hood requirements for those packages listed in the new file.
>
> This adds complexity, expand the window for frustration in first-time users, and covering that would leave instructions longer and longer.

**Comment by coelhudo** [comment]
I decided to generate the requirements file since Python already provides the package and environment management.

I understand the reason why conda was chosen as a way to deal with the dependencies. The idea was to provide an alternative for people that don't want to install conda, at the same time keeping conda as the primary way to manage all the dependencies without affecting first-time contributors. However, I can see how having both ways could add complexity since someone would have to check if the requirements file has the same versions as the packages managed by conda in case conda gets updated, albeit I believe that's something that doesn't happen frequently. 

I agree with you and I'm going to close it.
